"""add auth tables

Revision ID: 48bf85165597
Revises: 0001_initial
Create Date: 2026-06-15 12:31:52.832740
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48bf85165597'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create audit_logs table (new security-related table)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    
    # Create indexes on existing tables (safe operations)
    op.create_index(op.f('ix_auth_users_email'), 'auth_users', ['email'], unique=True)
    op.create_index(op.f('ix_registration_codes_code'), 'registration_codes', ['code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Reverse the safe operations in reverse order
    op.drop_index(op.f('ix_registration_codes_code'), table_name='registration_codes')
    op.drop_index(op.f('ix_auth_users_email'), table_name='auth_users')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
